baseURL: "https://andremrsantos.github.io" 
title: Ribeiro-dos-Santos Profile
theme: ["PaperMod", "hugo-simplecite"]
pagination.pagerSize: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["blog", "papers", "classes"]

minify:
  disableXML: true
  minifyOutput: true

params:
  title: Ribeiro-dos-Santos Profile
  description: "Ribeiro-dos-Santos Profile"
  keywords: [Blog, Portfolio, PaperMod]
  author: André M. Ribeiro-dos-Santos
  DateFormat: "January 2, 2006"
  defaultTheme: light # dark, light
  disableThemeToggle: false

  # ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  # ShowBreadCrumbs: true
  # ShowWordCount: true

  UseHugoToc: true
  comments: false
  hideMeta: false
  hideSummary: false
  ShowToc: true
  TocOpen: true
  
  comments: true

  MainSections: ["papers", "classes", "blog"]

  profileMode:
    enabled: true
    title: PhD. André M. Ribeiro-dos-Santos
    subtitle: "Bioinformatician working in gene regulation, population genetics, and machine learning. Currently working as visiting professor in Universidade Federal do Pará (UFPA, Belem - PA, BR)."
    imageUrl: "img/profile.jpeg"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Publications
        url: papers/
        weight: 5
      - name: Blog
        url: blog/
        weight: 2
      - name: Github
        url: https://github.com/andremrsantos
        weight: 1
      - name: Scholar
        url: https://scholar.google.com/citations?user=lMC_0XUAAAAJ
        weight: 1
  
  homeInfoParams:
    Title: PhD. André M. Ribeiro-dos-Santos
    Content: "Bioinformatician working in gene regulation, population genetics, and machine learning. Currently working as visiting professor in Universidade Federal do Pará (UFPA, Belem - PA, BR)."
    
  socialIcons:
    - name: bluesky
      url: https://bsky.app/profile/andremrsantos.bsky.social
    - name: github
      url: https://github.com/andremrsantos
    - name: googlescholar
      url: https://scholar.google.com/citations?user=lMC_0XUAAAAJ

menu:
  main:
    - name: Blog
      url: blog/
      weight: 1
    - name: Publications
      url: papers/
      weight: 2
    - name: Classes
      url: classes/
      weight: 3
    - name: Github
      url: https://github.com/andremrsantos
      weight: 4
    - name: Scholar
      url: https://scholar.google.com/citations?user=lMC_0XUAAAAJ
      weight: 5

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn 
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2

languages:
  en:
    # contentDir: content/en
    languageCode: en-US
    languageName: English
    weight: 10
    enable: true
  pt-br:
    # contentDir: content/ptbr
    languageCode: pt-BR
    languageName: Português Brasileiro
    weight: 20
    ## Menu translations
    params.profileMode:
      enable: true
      subtitle: "Professor Visitante na Pós-Graduação em Genética e Biologia Molecular (UFPA, Belém, PA - BR). Bioinformata desenvolvendo pesquisas em Regulação Gênica, Genética de Populações e Aprendizado de Máquina."
      buttons:
        - name: Publicações
          url: papers/
          weight: 5
        - name: Classes
          url: classes/
          weight: 4
        - name: Blog
          url: blog/
          weight: 2
        - name: Github
          url: https://github.com/andremrsantos
          weight: 1
        - name: Scholar
          url: https://scholar.google.com/citations?user=lMC_0XUAAAAJ
          weight: 1
    menus:
      main:
        - name: Blog
          url: blog/
          weight: 1
        - name: Publicações
          url: papers/
          weight: 2
        - name: Classes
          url: classes/
          weight: 3
        - name: Github
          url: https://github.com/andremrsantos
          weight: 4
        - name: Scholar
          url: https://scholar.google.com/citations?user=lMC_0XUAAAAJ
          weight: 5
